"""add is_active to equipment

Revision ID: 50ccc26f6180
Revises: 001_create_users
Create Date: 2025-10-15 10:41:31.732473

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '50ccc26f6180'
down_revision: Union[str, Sequence[str], None] = '001_create_users'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tb_equipments_id'), table_name='tb_equipments')
    op.drop_table('tb_equipments')
    op.create_index(op.f('ix_tb_users_email'), 'tb_users', ['email'], unique=True)
    op.create_index(op.f('ix_tb_users_id'), 'tb_users', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tb_users_id'), table_name='tb_users')
    op.drop_index(op.f('ix_tb_users_email'), table_name='tb_users')
    op.create_table('tb_equipments',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('codigo', sa.VARCHAR(), nullable=False),
    sa.Column('nome_do_posto', sa.VARCHAR(), nullable=False),
    sa.Column('razao_uso', sa.VARCHAR(length=14), nullable=False),
    sa.Column('versao_solucao', sa.VARCHAR(), nullable=False),
    sa.Column('descricao', sa.VARCHAR(), nullable=False),
    sa.Column('data_limite', sa.DATE(), nullable=False),
    sa.Column('responsavel', sa.VARCHAR(), nullable=False),
    sa.Column('status', sa.VARCHAR(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo')
    )
    op.create_index(op.f('ix_tb_equipments_id'), 'tb_equipments', ['id'], unique=False)
    # ### end Alembic commands ###
